name: Deploy Debian Repo and Sync to kttdebianrepo.work.gd

on:
  push:
    branches: [ main ]

env:
  REPO_DIR: ./debian-repo
  PUBLISH_BRANCH: gh-pages
  COMPONENT: main
  REMOTE_USER: your_server_user
  REMOTE_HOST: kttdebianrepo.work.gd
  REMOTE_REPO_PATH: /var/www/debian-repo
  REMOTE_NGINX_SERVICE: nginx

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y reprepro rsync ssh

      - name: Generate Debian repo
        run: |
          mkdir -p "$REPO_DIR/conf"
          cat > "$REPO_DIR/conf/distributions" <<EOF
Codename: sid
Suite: unstable
Components: ${COMPONENT}
Architectures: amd64 all
EOF

          mkdir -p "$REPO_DIR/pool/${COMPONENT}"
          mkdir -p "$REPO_DIR/dists"

          find $REPO_DIR/pool -type f -name "*.deb" | while read deb; do
            reprepro -b "$REPO_DIR" -S utils -P optional -C $COMPONENT includedeb sid "$deb" || true
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.REPO_DIR }}
          publish_branch: ${{ env.PUBLISH_BRANCH }}

      - name: Sync repo to your server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          rsync -avz --delete $REPO_DIR/ $REMOTE_USER@$REMOTE_HOST:$REMOTE_REPO_PATH/
          ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "sudo systemctl reload $REMOTE_NGINX_SERVICE"
