name: Deploy Debian Repo with GPG and Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup GPG
      env:
        GPG_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      run: |
        echo "$GPG_KEY" > kttdebianrepo.asc
        gpg --batch --import kttdebianrepo.asc
        rm kttdebianrepo.asc

    - name: Build Debian Repo (example)
      run: |
        # Your repo build commands here, e.g. reprepro calls
        echo "Build steps here"

    - name: Setup nginx
      run: |
        sudo apt-get update
        sudo apt-get install -y nginx
        # Configure nginx to serve ./debian at root
        echo 'server {
          listen 80;
          server_name krzysthetech.github.io;

          root $PWD/debian;
          autoindex on;

          location / {
            try_files $uri $uri/ =404;
          }
        }' | sudo tee /etc/nginx/sites-available/debian-repo

        sudo ln -sf /etc/nginx/sites-available/debian-repo /etc/nginx/sites-enabled/
        sudo systemctl restart nginx

    - name: Deploy Debian repo to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./debian
        publish_branch: gh-pages
