name: Deploy Debian Repo to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REPO_DIR: .
      PUBLISH_BRANCH: gh-pages
      COMPONENT: main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show repo files for debugging
        run: ls -l $REPO_DIR

      - name: Deploy Debian repo to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.REPO_DIR }}
          publish_branch: ${{ env.PUBLISH_BRANCH }}

      - name: Install and start nginx to serve repo (preview)
        if: true
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx
          sudo rm -rf /var/www/html/*
          sudo cp -r $REPO_DIR/* /var/www/html/
          sudo systemctl restart nginx
          echo "Nginx is serving the repo at http://localhost"
