name: Deploy Debian Repo with GPG and Nginx test

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REPO_DIR: ./debian
      PUBLISH_BRANCH: gh-pages

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup GPG key
      env:
        GPG_KEY_BASE64: ${{ secrets.GPG_PRIVATE_KEY_BASE64 }}
      run: |
        mkdir -p ~/.gnupg
        chmod 700 ~/.gnupg
        echo "$GPG_KEY_BASE64" | base64 -d > kttdebianrepo.asc
        gpg --batch --import kttdebianrepo.asc
        rm kttdebianrepo.asc
        gpg --list-keys

    - name: Show repo folder contents
      run: ls -l $REPO_DIR

    - name: Deploy Debian repo to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ env.REPO_DIR }}
        publish_branch: ${{ env.PUBLISH_BRANCH }}

    - name: Run nginx to serve repo (test)
      run: |
        docker run --rm -d -p 8080:80 \
          -v $PWD/$REPO_DIR:/usr/share/nginx/html:ro \
          nginx:alpine
      # Add a wait or curl test here if needed
