name: Build and Deploy Debian Repo

on:
  push:
    branches: [ main ]

env:
  REPO_DIR: ./debian
  DIST: sid
  COMPONENT: main
  DEPLOY_PATH: /var/www/kttdebianrepo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install reprepro
      run: |
        sudo apt-get update
        sudo apt-get install -y reprepro

    - name: Prepare Debian repo
      run: |
        mkdir -p $REPO_DIR/conf $REPO_DIR/pool/$COMPONENT
        echo "Codename: $DIST" > $REPO_DIR/conf/distributions
        echo "Suite: unstable" >> $REPO_DIR/conf/distributions
        echo "Components: $COMPONENT" >> $REPO_DIR/conf/distributions
        echo "Architectures: amd64 all" >> $REPO_DIR/conf/distributions

        # Include all .deb packages
        find $REPO_DIR/pool -type f -name "*.deb" | while read deb; do
          reprepro -b $REPO_DIR -S utils -P optional -C $COMPONENT includedeb $DIST "$deb" || true
        done

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Rsync repository to kttdebianrepo.work.gd
      run: |
        rsync -avz --delete $REPO_DIR/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:$DEPLOY_PATH/
