name: Deploy Debian Repo

on:
  push:
    branches: [ main ]

env:
  REPO_DIR: .
  PUBLISH_BRANCH: gh-pages
  COMPONENT: main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Debian repository with reprepro
        run: |
          sudo apt-get update
          sudo apt-get install -y reprepro nginx

          mkdir -p "$REPO_DIR/conf"
          cat > "$REPO_DIR/conf/distributions" <<EOF
Codename: sid
Suite: unstable
Components: ${COMPONENT}
Architectures: amd64 all
EOF

          mkdir -p "$REPO_DIR/pool/${COMPONENT}"
          mkdir -p "$REPO_DIR/dists"

          # Add any .deb packages found
          find $REPO_DIR/pool -type f -name "*.deb" | while read deb; do
            reprepro -b "$REPO_DIR" -S utils -P optional -C $COMPONENT includedeb sid "$deb" || true
          done

      - name: Start nginx to serve repo on port 8080
        run: |
          sudo mkdir -p /var/www/html
          sudo cp -r $REPO_DIR/* /var/www/html/
          sudo sed -i 's|listen 80 default_server|listen 8080 default_server|g' /etc/nginx/sites-available/default
          sudo sed -i 's|root /var/www/html;|root /var/www/html; autoindex on;|' /etc/nginx/sites-available/default
          sudo nginx -t
          sudo systemctl restart nginx
          echo "Repo is now being served at http://$(curl -s ifconfig.me):8080"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.REPO_DIR }}
          publish_branch: ${{ env.PUBLISH_BRANCH }}
