name: Build and Deploy Debian Repo

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Debian repo build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y reprepro dpkg-dev gzip xz-utils

      - name: Build repo metadata with reprepro
        run: |
          bash ./scripts/build-repo.sh
        # Make sure your build script is at ./scripts/build-repo.sh and executable

      - name: Deploy to GitHub Pages (gh-pages branch)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./KTT-Debian-Repo
          publish_branch: gh-pages
